### ISSUE TITLE
Hi! I'm MIA2032

### ISSUE THREAD

**Issue by legoboyvdlp** [Flymerlion/Liveries#1]
I have all the planes here. Not sure about liveries...
www.github.com/FGMEMBERS/A320neo
Also https://github.com/FGMEMBERS/A320neo/tree/narendran for the old, omega, version.
https://github.com/FGMEMBERS/A330-300
https://github.com/FGMEMBERS/A330-200
https://github.com/FGMEMBERS/A380-omega
https://github.com/FGMEMBERS/E-jet-family
https://github.com/FGMEMBERS/ATR-72-500
https://github.com/FGMEMBERS/ATR-42-500

Don't have the 757-200PF, or the 777-F mod.
Any others?

**Comment by OsuKrafter** [comment]
Thanks for collaborating with Merlion.
